---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  # default. Use `kubectl get sc` too what storage classes are configured
  storageClassName: standard  # for kind
  # storageClassName: "gp2"  # for eks
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 3Gi
